name: core_cli
description: Simple core to create your CLI.
version: 1.0.0
homepage: https://mateussiqueira.dev/core-cli
environment:
  sdk: '>=2.17.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  faker: ^2.0.0
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {args: ^2.3.1}
